### ISSUE TITLE
Adam(0) fails

### ISSUE THREAD

**Issue by cossio** [FluxML/Optimisers.jl#119]
### Package Version

0.2.10

### Julia Version

1.8.3

### OS / Environment

Linux

### Describe the bug

Cannot create rule (e.g. `Adam`) with integer learning rate.

### Steps to Reproduce

```
julia> Adam(0) # any integer learning rate
```

### Expected Results

`Adam(0.0)` works fine. I believe `Adam(0)` should behave like `Adam(0.0)`.

### Observed Results

```
ERROR: MethodError: no method matching eps(::Type{Int64})
Closest candidates are:
  eps() at float.jl:831
  eps(::AbstractFloat) at float.jl:827
  eps(::T) where T<:Dates.TimeType at ~/.julia/juliaup/julia-1.8.3+0.x64/share/julia/stdlib/v1.8/Dates/src/types.jl:444
  ...
Stacktrace:
 [1] Adam(η::Int64)
   @ Optimisers ~/.julia/packages/Optimisers/GKFy2/src/rules.jl:205
 [2] top-level scope
   @ REPL[28]:1
```

**Comment by mcabbott** [comment]
So the obvious answer is to insert `float` at many places so that these agree. 

One quirk of the present design is that all small avoid-zero parameters are `eps(η)` and hence follow its type:
```julia
julia> Adam(0.0f0)
Adam{Float32}(0.0f0, (0.9f0, 0.999f0), 1.1920929f-7)

julia> Adam(0.0)
Adam{Float64}(0.0, (0.8999999761581421, 0.9990000128746033), 2.220446049250313e-16)
```
But when they are used, they are often added to numbers from the parameter arrays / gradients instead. Should their size follow those types? Or be fixed at `1e-8` or something?

**Comment by mcabbott** [comment]
There is a parameter Adam{T}, just for simplicity there's only one T. This could be made using `promote` on all the supplied numbers, but right now simply follows the learning rate. 

`update` is careful about preserving eltype, a wider T will not produce wider arrays. It will just mean that some intermediate calculations happen in the larger type. 

`eps` is a hyperparameter. Its default at present is always `eps(typeof(eta))`. My query is whether this makes much sense, since `eta::Float64` most likely just means you typed it in this way, not that the model is in high precision.
